case class Work(name:String)
case class ErrorMessage(error: String, actorAddress: String)
case class ActorPoll(value:List[String])
class RestartMeException extends Exception("RESTART")
class ResumeMeException extends Exception("RESUME")
